[SDESK-803] - Extract Commission desk story from Legal Archive and make it available in Text Archive.
superdesk/superdesk-aap pull request #242
Opened 2017-03-01 04:57 UTC by MarkLark86

2017-03-01 06:33 UTC, mdhaman commented on server/aap/commands/export_legal_archive_to_archive.py
> +            # from pprint import pprint
remove comments.

2017-03-01 11:58 UTC, akintolga requested changes

2017-03-01 11:58 UTC, akintolga commented on server/aap/commands/export_legal_archive_to_archive.py
> +        :return dict: archive item converted from legal archive item
Even though it is self evident I think it is good practice to add all parameters to the comments.

2017-03-01 11:58 UTC, akintolga commented on server/aap/commands/export_legal_archive_to_archive.py
> +        rtn = deepcopy(item)
Instead of short variable names please use something more readable if possible.

2017-03-01 11:58 UTC, akintolga commented on server/aap/commands/export_legal_archive_to_archive.py
> +            self._export_to_archive()
`_export_to_archive` can return None if desk is not found so it may be better to log another message like `Completed bot nothing exported..`

2017-03-01 12:00 UTC, akintolga commented
Looks good except few minor comments. It would be good if a test or two is added.

2017-03-03 20:09 UTC, akintolga approved these changes

2017-03-06 03:18 UTC, merged